services:
  mongodb:
    image: mongodb:latest
    container_name: db
    build:
      context: .
      args:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: Your_Super_Secret_Password_For_MongoDB_Root_User_Account_123_456_789
    volumes:
      - ./db:/data/db # Replace with your volume mapping if needed
      - ./backup:/backup # Replace with your volume mapping if needed
    ports:
      - "27017:27017" # Map host port 27017 to container port 27017